取消失败重试

diff --git a/.github/workflows/build-Image.yml b/.github/workflows/build-Image.yml
--- a/.github/workflows/build-Image.yml
+++ b/.github/workflows/build-Image.yml
@@ -65,7 +65,8 @@ jobs:
       run: |
         # export THREADCOUNT=100%
         env
-        make image || THREADCOUNT=1 make image ||  THREADCOUNT=1 make image V=s
+        make image 
+        #|| (echo '=======ERROR===============' && THREADCOUNT=1 make image) ||  THREADCOUNT=1 make image V=s
         echo "::set-output name=status::success"
     - name: Upload ARTIFACT
       uses: actions/upload-artifact@v2
